# TCL File Generated by Component Editor 10.1sp1
# Fri Jan 27 01:47:44 BRST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | fft_pipeline "fft_pipeline" v1.0
# | Danilo Pagano 2012.01.27.01:47:44
# | 
# | 
# | C:/altera/Projetos/fftNIOS/fft_pipeline.vhd
# | 
# |    ./C:/altera/Projetos/ProjetosMestrado/FFT_CIII/tipos.vhd syn, sim
# |    ./componentes.vhd syn, sim
# |    ./fft_pipeline.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module fft_pipeline
# | 
set_module_property NAME fft_pipeline
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP FFT
set_module_property AUTHOR "Danilo Pagano"
set_module_property DISPLAY_NAME fft_pipeline
set_module_property TOP_LEVEL_HDL_FILE fft_pipeline.vhd
set_module_property TOP_LEVEL_HDL_MODULE fft_pipeline
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file C:/altera/Projetos/ProjetosMestrado/FFT_CIII/tipos.vhd {SYNTHESIS SIMULATION}
add_file componentes.vhd {SYNTHESIS SIMULATION}
add_file fft_pipeline.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 wr_data writedata Input 32
add_interface_port avalon_slave_0 cs chipselect Input 1
add_interface_port avalon_slave_0 wr write Input 1
add_interface_port avalon_slave_0 addr address Input 11
add_interface_port avalon_slave_0 rd_data readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end counter export Output 10
add_interface_port conduit_end tx_out export Output 1
add_interface_port conduit_end rx_in export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink clr_n reset Input 1
# | 
# +-----------------------------------
